blank_issues_enabled: false

# <go-bootstrap> Redirect support questions
# contact_links:
#   - name: â“ Question
#     url: https://github.com/<org>/<repo>/discussions
#     about: Ask or discuss with us, we're happy to help ğŸ™‹
